#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 yujiando11
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans=1.0
for line in sys.stdin:
    try:
        ans/=float(line)
        print(ans)
    except ZeroDivisionError:
        print("0割できません")

