 name: test_minus        
 on: push          
 jobs:            
    test_minus:           
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.7","3.8","3.9","3.10"] 
      steps:
      - uses: actions/checkout@v3            
      - name: All test_minus           
        run: bash -xv ./test_minus.bash
